version: '3'
services:
  grafana:
    image: "grafana/grafana:master"
    container_name: grafana
    volumes:
      - .:/var/lib/grafana
    ports:
     - "3000:3000"
    networks:
     - coverage
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.6.0"
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
     - coverage
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.0"
    container_name: elasticsearch
    volumes:
      - .:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - coverage
networks:
  coverage:
